
import { Wine } from './types';

export const COLORS = {
  primary: '#722f3f',
  secondary: '#d4af37',
  background: '#faf8f5',
  text: '#2a2a2a',
  neutral: '#e8e6e1',
  accent: '#2d7a5e'
};

export const MOCK_WINES: Wine[] = [
  {
    id: '1',
    name: 'Estate Cabernet Sauvignon',
    type: 'Red',
    drinkCategory: 'Wine',
    vintage: 2019,
    varietal: 'Cabernet Sauvignon',
    region: 'Napa Valley, CA',
    price: 125,
    abv: '14.5%',
    tastingNotes: ['Blackberry', 'Cassis', 'Tobacco', 'Oak'],
    foodPairings: ['Grilled Ribeye', 'Aged Cheddar', 'Lamb Chops'],
    body: 'Full',
    tannins: 'High',
    acidity: 'Medium',
    rating: 96,
    awards: ['Decanter World Wine Awards - Platinum', '98 Points - Wine Spectator'],
    imageUrl: '/Wine.png',
    description: 'A robust and elegant Cabernet Sauvignon with deep layers of complexity and a long, velvety finish.',
    stock: 24,
    certifications: ['Organic', 'Sustainable']
  },
  {
    id: '2',
    name: 'Reserve Chardonnay',
    type: 'White',
    drinkCategory: 'Wine',
    vintage: 2021,
    varietal: 'Chardonnay',
    region: 'Sonoma Coast, CA',
    price: 85,
    abv: '13.8%',
    tastingNotes: ['Lemon Curd', 'Toasted Brioche', 'Vanilla Bean'],
    foodPairings: ['Lobster Thermidor', 'Roast Chicken', 'Creamy Risotto'],
    body: 'Medium',
    tannins: 'Low',
    acidity: 'High',
    rating: 94,
    awards: ['95 Points - James Suckling'],
    imageUrl: '/Wine2.png',
    description: 'Beautifully balanced with crisp acidity and a rich, buttery texture from French oak aging.',
    stock: 45,
    certifications: ['Vegan']
  },
  {
    id: '3',
    name: 'Premium Old Vine Zinfandel',
    type: 'Red',
    drinkCategory: 'Wine',
    vintage: 2020,
    varietal: 'Zinfandel',
    region: 'Lodi, CA',
    price: 65,
    abv: '15.2%',
    tastingNotes: ['Raspberry Jam', 'Black Pepper', 'Cocoa'],
    foodPairings: ['BBQ Brisket', 'Spicy Sausage', 'Dark Chocolate'],
    body: 'Full',
    tannins: 'Medium',
    acidity: 'Medium',
    rating: 92,
    awards: ['Best in Class - SF Chronicle Wine Competition'],
    imageUrl: '/Wine3.png',
    description: 'Intense fruit flavors from 80-year-old vines, showcasing the bold spirit of California Zinfandel.',
    stock: 18,
    certifications: ['Organic']
  },
  {
    id: '4',
    name: 'Provencal Style Rosé',
    type: 'Rosé',
    drinkCategory: 'Wine',
    vintage: 2022,
    varietal: 'Grenache Blend',
    region: 'Santa Ynez Valley, CA',
    price: 38,
    abv: '12.5%',
    tastingNotes: ['Strawberry', 'Watermelon', 'Wet Stone'],
    foodPairings: ['Fresh Oysters', 'Nicoise Salad', 'Goat Cheese'],
    body: 'Light',
    tannins: 'Low',
    acidity: 'High',
    rating: 91,
    awards: ['Double Gold - International Rosé Championship'],
    imageUrl: '/Wine4.png',
    description: 'A bone-dry, pale pink rosé that captures the essence of summer with vibrant acidity.',
    stock: 60,
    certifications: ['Sustainable', 'Vegan']
  },
  {
    id: '5',
    name: 'Super Grand Cuvée Brut',
    type: 'Sparkling',
    drinkCategory: 'Champagne',
    vintage: 2018,
    varietal: 'Pinot Noir',
    region: 'Carneros, CA',
    price: 95,
    abv: '12.0%',
    tastingNotes: ['Green Apple', 'Almond', 'Fine Bubbles'],
    foodPairings: ['Caviar', 'Fried Calamari', 'Celebrations'],
    body: 'Medium',
    tannins: 'Low',
    acidity: 'High',
    rating: 95,
    awards: ['96 Points - Decanter'],
    imageUrl: '/Wine6.png',
    description: 'Method Traditionnelle sparkling wine with persistent perlage and sophisticated aromatics.',
    stock: 12,
    certifications: ['Sustainable']
  },
  {
    id: '6',
    name: 'Highland Pinot Noir',
    type: 'Red',
    drinkCategory: 'Wine',
    vintage: 2020,
    varietal: 'Pinot Noir',
    region: 'Willamette Valley, OR',
    price: 78,
    abv: '13.5%',
    tastingNotes: ['Cherry', 'Forest Floor', 'Clove'],
    foodPairings: ['Roasted Duck', 'Wild Mushroom Pasta', 'Salmon'],
    body: 'Light',
    tannins: 'Medium',
    acidity: 'High',
    rating: 93,
    awards: ['Top 100 Wines of 2023'],
    imageUrl: '/Wine5.png',
    description: 'An ethereal expression of cool-climate Pinot Noir with delicate fruit and earthy undertones.',
    stock: 30,
    certifications: ['Organic', 'Vegan']
  },
  {
    id: '7',
    name: 'The Macallan Double Cask 12',
    type: 'Dessert',
    drinkCategory: 'Scotch Whisky',
    vintage: '12 Years',
    varietal: 'Single Malt Scotch',
    region: 'Speyside, Scotland',
    price: 95,
    abv: '43%',
    tastingNotes: ['Honey', 'Dried Fruit', 'Citrus'],
    foodPairings: ['Dark Chocolate', 'Aged Cheese'],
    body: 'Full',
    tannins: 'Low',
    acidity: 'Low',
    rating: 94,
    awards: ['Gold - San Francisco World Spirits'],
    imageUrl: '/Wine7.png',
    description: 'A classic Speyside malt with a balance of American and European oak casks.',
    stock: 15
  },
  {
    id: '8',
    name: 'Patron Silver Tequila',
    type: 'White',
    drinkCategory: 'Tequila & Mezcal',
    vintage: 'N/A',
    varietal: '100% Blue Agave',
    region: 'Jalisco, Mexico',
    price: 55,
    abv: '40%',
    tastingNotes: ['Agave', 'Citrus', 'White Pepper'],
    foodPairings: ['Tacos', 'Ceviche'],
    body: 'Medium',
    tannins: 'Low',
    acidity: 'Medium',
    rating: 92,
    awards: ['Premium Selection'],
    imageUrl: '/Wine8.png',
    description: 'A smooth and sweet tequila with a light pepper finish.',
    stock: 22
  },
  {
    id: '9',
    name: 'Hola Atlas Peak Syrah',
    type: 'Red',
    drinkCategory: 'Wine',
    vintage: 2018,
    varietal: 'Syrah',
    region: 'Atlas Peak, Napa Valley',
    price: 110,
    abv: '14.8%',
    tastingNotes: ['Blueberry', 'Smoked Meat', 'Espresso', 'Violets'],
    foodPairings: ['Slow-Roasted Lamb', 'Game Meats', 'Stilton Cheese'],
    body: 'Full',
    tannins: 'High',
    acidity: 'Medium',
    rating: 95,
    awards: ['97 Points - Robert Parker'],
    imageUrl: '/Wine9.png',
    description: 'A powerful, mountain-grown Syrah with incredible concentration and savory complexity.',
    stock: 14,
    certifications: ['Organic']
  },
  {
    id: '10',
    name: 'Top Heritage XO Cognac',
    type: 'Dessert',
    drinkCategory: 'Cognac & Brandy',
    vintage: 'XO',
    varietal: 'Champagne Blend',
    region: 'Cognac, France',
    price: 240,
    abv: '40%',
    tastingNotes: ['Dried Apricot', 'Cinnamon', 'Leather', 'Sandalwood'],
    foodPairings: ['Foie Gras', 'Crème Brûlée', 'Hand-Rolled Cigars'],
    body: 'Full',
    tannins: 'Low',
    acidity: 'Low',
    rating: 97,
    awards: ['Platinum - Spirits Selection'],
    imageUrl: '/Wine13.png',
    description: 'A masterpiece of blending, featuring eaux-de-vie aged for up to 30 years in Limousin oak.',
    stock: 8
  },
  {
    id: '11',
    name: 'Botanical Reserve Gin',
    type: 'White',
    drinkCategory: 'Gin',
    vintage: 'Small Batch',
    varietal: 'London Dry Style',
    region: 'Surrey, UK',
    price: 62,
    abv: '47%',
    tastingNotes: ['Juniper', 'Kaffir Lime', 'Coriander Seed', 'Elderflower'],
    foodPairings: ['Smoked Salmon', 'Cucumber Sandwiches'],
    body: 'Medium',
    tannins: 'Low',
    acidity: 'Medium',
    rating: 93,
    awards: ['World Gin Awards - Gold'],
    imageUrl: '/Wine11.png',
    description: 'An exceptionally smooth gin infused with 14 rare botanicals for a complex, floral profile.',
    stock: 35
  },
  {
    id: '12',
    name: 'Marlborough Reserve Sauvignon Blanc',
    type: 'White',
    drinkCategory: 'Wine',
    vintage: 2023,
    varietal: 'Sauvignon Blanc',
    region: 'Marlborough, NZ',
    price: 45,
    abv: '13.0%',
    tastingNotes: ['Passionfruit', 'Fresh Grass', 'Grapefruit', 'Mineral'],
    foodPairings: ['Grilled Asparagus', 'Goat Cheese Salad', 'White Fish'],
    body: 'Light',
    tannins: 'Low',
    acidity: 'High',
    rating: 94,
    awards: ['95 Points - Sam Kim'],
    imageUrl: '/Wine14.png',
    description: 'A vibrant and aromatic Sauvignon Blanc with zesty acidity and intense tropical fruit notes.',
    stock: 52,
    certifications: ['Sustainable']
  },
  {
    id: '13',
    name: 'Vintage 20yr Tawny Port',
    type: 'Dessert',
    drinkCategory: 'Wine',
    vintage: '20 Year',
    varietal: 'Nacional Blend',
    region: 'Douro Valley, Portugal',
    price: 98,
    abv: '20%',
    tastingNotes: ['Roasted Nuts', 'Butterscotch', 'Dried Fig', 'Orange Peel'],
    foodPairings: ['Blue Cheese', 'Walnut Tart', 'Dark Chocolate'],
    body: 'Full',
    tannins: 'Low',
    acidity: 'Medium',
    rating: 96,
    awards: ['Trophy - International Wine Challenge'],
    imageUrl: '/Wine10.png',
    description: 'Exquisite maturity and elegance, with a silky texture and a long, nutty finish.',
    stock: 12
  },
  {
    id: '14',
    name: 'Aged Caribbean Black Rum',
    type: 'Dessert',
    drinkCategory: 'Rum',
    vintage: '15 Years',
    varietal: 'Molasses Based',
    region: 'Barbados',
    price: 85,
    abv: '43%',
    tastingNotes: ['Molasses', 'Vanilla', 'Burnt Sugar', 'Tropical Spice'],
    foodPairings: ['Caramel Cake', 'Fried Plantains'],
    body: 'Full',
    tannins: 'Low',
    acidity: 'Low',
    rating: 94,
    awards: ['Gold - Rum Masters'],
    imageUrl: '/Wine12.png',
    description: 'A rich, dark rum aged in former bourbon casks, offering deep notes of caramel and oak.',
    stock: 20
  }
];
